collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Published", name: "published", widget: "boolean" }